### ISSUE TITLE
generate checkstyle.html from checkstyle.xml

### ISSUE THREAD

**Issue by abhisheknoldus** [checkstyle/contribution#108]
How can one use checkstyle xsl file to generate checkstyle html file .

**Comment by MEZk** [comment]
@abhisheknoldus 
Hello!

1) You can use ant in order to generate html file from checkstyle's xml-report with xsl. For example:
```xml
  <target name="report.checkstyle">
    <xslt in="checkstyle_report.xml"
          out="checkstyle_report.html"
          style="checkstyle-noframes-severity-sorted.xsl"/>
  </target>
```

where
checkstyle_report.xml - Checkstyle's report xml-file.
checkstyle_report.html - output html file.
checkstyle-noframes-severity-sorted.xsl - xsl transformation schema. Available schemas are located [here](https://github.com/checkstyle/contribution/tree/master/xsl).

2) You can use online xsl transformer http://www.freeformatter.com/xsl-transformer.html

**Comment by romani** [comment]
Answer is full enough, I am closing the issue.

**Comment by romani** [comment]
It is also possible to convert xml by shell - http://xmlsoft.org/XSLT/xsltproc.html
by maven plugin - http://www.mojohaus.org/xml-maven-plugin/examples/transform-basic.html
