### ISSUE TITLE
automate checkstyle-tester for diff report generation

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#51]
checkstyle-tester should have a mode to completely automatically generate diff report base on:
- latest binaries of chekcstyle (we could use our SNAPSHOT maven repo)
- "link" to patch (or some other way defining new binaries)
- config to run 

result should be ready to upload to github.io folder with report.

**Comment by MEZk** [comment]
@romani 
We can improve the tool (launch_diff.sh) designed by @rnveach .
I am able to generate diff reports with the tool. However, it needs to receive the following parameters which now are specified directly in the script:

MINIMIZE
CONTACTSERVER
CHECKSTYLE_DIR
TESTER_DIR
EXTRA_DIR
FINAL_RESULTS_DIR
DIFF_JAR
PULL_REMOTE

>latest binaries of chekcstyle (we could use our SNAPSHOT maven repo)

Why can't we run mvn install on the latest master? If we use SNAPSHOT maven repo it will require additional logic to grap the latest SNAPSHOT.

>"link" to patch (or some other way defining new binaries)

There is no need in passing the link. With @rnveach 's script it is generated and used automatically. We can generate before/after reports in the root of checkstyle-tester (for example in checkstyle-tester/reports-tmp), generate diff report in checkstyle-tester/diff-report and remove reports-tmp. So, final reports will be located at checkstyle-tester/diff-report.

>config to run

Now the script has an option which allows to specify Checkstyle config for the tester.

**Comment by romani** [comment]
> We can improve the tool (launch_diff.sh) designed by @rnveach .

yes reusage of exisinng is good.
The only concern for me is that usage of shell there might be not a good idea. Big shell files are hard to maintain.
@rnveach , does it make sense to rewrite it to groovy (java scripting language) ?
Most CIs support it, it should not be a problems for contributors to run groovy too. Probably we could make it work on Windows too.

> However, it needs to receive the following parameters which now are specified directly in the script

all that variables should be based on filesystem where clone for contribution repo was done. All additional clones generations should happen under some inner folder.
It might be good to be all that variables to be customizable to let tune it, but it should work by default without any extra steps/configurations.

> Why can't we run mvn install on the latest master?

no problem, it was just an idea, use what ever is convenient.

> There is no need in passing the link. 

by link I meant some indentifier of path - "username" and "branch". Example - https://github.com/checkstyle/checkstyle/blob/master/fast-forward-merge.sh#L14

> Now the script has an option which allows to specify Checkstyle config for the tester.

good. Script usage should be focused on user that that did his first PR to checkstyle and now he need to generate diff report.
So, steps should be like:
1) "git clone https://....conttibution"
2) "cd folder-with-script"
3) change configuration file to contain his Check
4) change file that define list of projects
5) "./generete-diff-report.sh github-username branch-with-fix"
6) instructions on how to put that report(ready to copy folder) to github.io .

attention - there is no extra confgurations, all should be by default stored/cloned/generated in some work folder close to launched shell script.

**Comment by rnveach** [comment]
> does it make sense to rewrite it to groovy (java scripting language) ?

I never worked with groovy myself, never actually worked with bash before this script too. As long as the new language supports executing command lines (git, maven, and diff utility), getting their return code (success/failure), and reading/modifying files then we can rewrite it.

I do dislike rewriting big stuff just to support newer languages/features, but supporting Windows does sound like a good reason and will allow me to drop my VM which I mostly keep around for running regression reports.

I do have a web version that uses `launch_diff.sh` to easily run reports on demand from non-public URL similar to `checkstyle-web-tester`. It currently relies on `launch_diff.sh` being set up for that specific user's repository and remote and doesn't support multiple requests at the same time, so it would need changes for public use if we wanted to go that way.

> Most CIs support it

Are we going to attach this to a CI?
Usually CIs don't allow outputing files easily and depending on the number of projects, a run can take up to 30-40 minutes. Also depending on number of violations, output could be big as we keep original Java files.

> all that variables should be based on filesystem where clone for contribution repo was done.

I agree. They should all be relative and set base folder on start of execution. I went with full paths in the script to avoid any issues since we change directories and reference others alot in the script.

> 4) Run mvn package inside ./../patch-diff-report-tool and get the lates diff tool jar.

Agree. It should be changed and saved in a location so consecutive runs don't need to regenerate it.

> 4) change file that define list of projects

We should default to all 'workable' projects, as we never know where we will find the one file that has an issue with change. First time users probably will never change this file when asked to run.

**Comment by romani** [comment]
>I do dislike rewriting big stuff just to support newer languages/features

Writing huge shell script is a disaster for future updates, in my experience. We should stop investing to shell as amount of IF statements grow. As groovy it could be updated by any java enginer, but shell suport is always a strughle even for experiened.

> Are we going to attach this to a CI?

Not now, but most likely as found it stable and know what we want to catch. I more like our execution on projects thay already enfoce checkstyle.

**Comment by rnveach** [comment]
While we are working on this, it would be nice if we could support sevntu regression with these scripts.

**Comment by rnveach** [comment]
Script is added

**Comment by romani** [comment]
All except for distellici are switched to groovy. Task is closed.
