### ISSUE TITLE
Fix IDEA  inspection violations of engine 2020.1.1

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#626]
for now I set build failure if we introduce more than 66 errors and 6 warns (current master counts of violations)

![image](https://user-images.githubusercontent.com/812984/181024065-66e6a997-316b-449b-aa0e-2f86660c28b8.png)

**Comment by rnveach** [comment]
I updated TC to now require 0 errors again
https://teamcity.jetbrains.com/buildConfiguration/Checkstyle_ContributionIdeaInspectionsMaster/3952829?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandCode+inspection=true

This issue is resolved and closed
